apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-mysql
  namespace: production
spec:
  selector:
    matchLabels:
      app: ecommerce-mysql
  template:
    metadata:
      labels:
        app: ecommerce-mysql
    spec:
      terminationGracePeriodSeconds: 10 # wait for 10 seconds before killing the pod
      containers:
        - name: ecommerce-mysql
          image: mysql:8.4
          env: # environment variables
            - name: MYSQL_ROOT_PASSWORD
              value: api_root
            - name: MYSQL_USER
              value: ecommerce
            - name: MYSQL_DATABASE
              value: ecommerce_auth
            - name: MYSQL_PASSWORD
              value: api
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: "150Mi"
              cpu: "100m"
          ports:
            - name: ecommerce-mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-local-storage
              mountPath: /var/lib/mysql
              subPath: mysql
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysql -h127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD ping
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: mysql-local-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
