apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-kibana
  template:
    metadata:
      labels:
        app: e-kibana
    spec:
      containers:
        - name: e-kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              memory: "1Gi"
              cpu: "250m"
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port>
              value: "http://e-elasticsearch.production.svc.cluster.local:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "kibana"
          ports:
            - name: e-kibana
              containerPort: 5601
