apiVersion: v1
kind: Service
metadata:
  name: e-kibana
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: e-kibana
  ports:
    - name: e-kibana
      protocol: TCP
      port: 5601
      targetPort: 5601
