apiVersion: v1
kind: Service
metadata:
  name: e-order
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: e-order
  ports:
    - name: order
      protocol: TCP
      port: 4006
      targetPort: 4006
