apiVersion: v1
kind: Service
metadata:
  name: ecommerce-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ecommerce-postgres
  ports:
    - name: ecommerce-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
