apiVersion: v1
kind: Service
metadata:
  name: ecommerce-redis
  namespace: production
spec:
  type: ClusterIP # "ClusterIP" means a service will only be accessible inside the cluster, via the cluster IP.
  # every pod with this selectors, we want attact services to that port
  selector:
    app: ecommerce-redis
  ports:
    - name: ecommerce-redis
      port: 6379
      targetPort: 6379
