apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: ecommerce-mongo
  ports:
    - name: ecommerce-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
