apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommerce-mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: ecommerce-mongo
  serviceName: ecommerce-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-mongo
    spec:
      containers:
        - name: ecommerce-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: ecommerce-mongo
          volumeMounts:
            - name: mongo-local-storage
              mountPath: /data/db
      volumes:
        - name: mongo-local-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
