apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-secrets
  namespace: production
type: Opaque
data:
  # echo -n <secret> | base64
  # echo -n base64-encoded | base64 --decode
  secret-key-one: MDMyYzVjM2NmYzM3OTM4YWU2ZGQ0M2QzYTNlYzc4MzQ=
  secret-key-two: ZDY2ZTM3NzAxOGMwYmMwYjU3NzJiYmM5YjEzMWU2ZDk=
  gateway-jwt-token: MTI4MjcyMmI5NDJlMDhjOGE2Y2IwMzNhYTZjZTg1MGU=
  jwt-token: OGRiOGY4NTk5MWJiMjhmNDVhYzAxMDdmMmExYjM0OWM=
  # redis://:thisismyownpassword123@@ecommerce-redis.production.svc.cluster.local:6379
  ecommerce-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAZWNvbW1lcmNlLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  # SENDER_EMAIL=winfield.breitenberg@ethereal.email
  # SENDER_EMAIL_PASSWORD=YMxWheJCNAN33qRWUj
  sender-email: d2luZmllbGQuYnJlaXRlbmJlcmdAZXRoZXJlYWwuZW1haWw=
  sender-email-password: WU14V2hlSkNOQU4zM3FSV1Vq
  ecommerce-mysql-db: bXlzcWw6Ly9lY29tbWVyY2U6YXBpQGVjb21tZXJjZS1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvZWNvbW1lcmNlX2F1dGg=
  ecommerce-postgres-host: ""
  ecommerce-postgres-user: ZWNvbW1lcmNl
  ecommerce-postgres-password: YXBp
  cloud-name: ZGczZnNhcHp1
  cloud-api-key: Nzk5NDgzNjkyMjE0NzM1
  cloud-api-secret: M0UwVk4yWWtDVnlNamxCV1VtUTd6T2Rrb0Iw
  cloud-folder: ZWNvbW1lcmNl
  # mongodb://ecommerce-mongo.production.svc.cluster.local/ecommerce
  mongo-database-url: bW9uZ29kYjovL2Vjb21tZXJjZS1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsL2Vjb21tZXJjZQ==
  # stripe-api-key:
  # stripe-client-key:
  ecommerce-rabbitmq-user: ZWNvbW1lcmNl
  ecommerce-rabbitmq-password: YXBp
  # amqp://ecommerce:api@ecommerce-queue.production.svc.cluster.local:5672
  ecommerce-rabbitmq-endpoint: YW1xcDovL2Vjb21tZXJjZTphcGlAZWNvbW1lcmNlLXF1ZXVlLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mg==
  # # http://elastic:admin1234@e-elasticsearch.production.svc.cluster.local:9200
  ecommerce-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QGUtZWxhc3RpY3NlYXJjaC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA=
  ecommerce-elastic-apm-server-url: ""
  ecommerce-elastic-apm-secret-token: ""
  ecommerce-elasticsearch-host: ZS1lbGFzdGljc2VhcmNoLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  ecommerce-elasticsearch-username: ZWxhc3RpYw==
  ecommerce-elasticsearch-password: YWRtaW4xMjM0
  ecommerce-elastic-cloud-id: ""
  # <elasticsearch-username>:
  ecommerce-elastic-cloud-auth: ""
