apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  # dont need namespace, because PV is cluster-wide
  # namespace: production
spec:
  storageClassName: rabbitmq-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: production
spec:
  storageClassName: rabbitmq-local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
