apiVersion: v1
kind: Service
metadata:
  name: ecommerce-queue
  namespace: production
spec:
  selector:
    app: ecommerce-queue
  ports:
    - name: queue
      port: 5672
      targetPort: queue
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
