apiVersion: v1
kind: Service
metadata:
  name: e-review
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: e-review
  ports:
    - name: review
      protocol: TCP
      port: 4007
      targetPort: 4007
